service: goals

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - '@slightlytyler/serverless-webpack'

custom:
  webpack: ./dev/build/config.js

functions:
  createRecord:
    handler: goals.createRecord
    events:
      - http:
          path: goals
          method: post
  fetchCollection:
    handler: goals.fetchCollection
    events:
      - http:
          path: goals
          method: get
